default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: db
  port: 5432

development:
  <<: *default
  database: codequestmanager_development

test:
  <<: *default
  database: codequestmanager_test

production:
  <<: *default
  database: codequestmanager_production
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
